### ISSUE TITLE
Precision mismatch

### ISSUE THREAD

**Issue by svenpanne** [kripken/BananaBread#42] opened 2013-12-10 15:14 UTC
A few months ago, some WebGL conformance fixes were made for Chrome: https://code.google.com/p/chromium/issues/detail?id=249018  These fixes include a check that the precision of uniforms match when linking GLSL programs, which is necessary for e.g. https://www.khronos.org/registry/webgl/conformance-suites/1.0.2/conformance/glsl/misc/shader-with-global-variable-precision-mismatch.html

I am not sure if it is a bug in BananaBread itself or the demo on https://developer.mozilla.org/demos/detail/bananabread, but with recent Chrome versions containing this new check, this leads to some shaders not linking, which again results in strange colors and some output of the form

   [STDOUT] Uniforms with the same name but different type/precisio

in the console. FireFox is not WebGL conformant in this respect (see Khronos link above) and happily links the program nevertheless, so the demo works with it.

In detail the problem is as follows: In the vertex shader (which uses "precision highp float" per default, see GLSL spec) we have:

   uniform vec4 waterfadeparams;

and in the fragment shader (which has no default for float) we have:

   precision mediump float;
   uniform vec4 waterfadeparams;

Chrome correctly detects the precision mismatch and refuses to link the program. There are several other uniforms in the demo with similar problems: depthfxparams, envscale, glowcolor, lightdir, lightscale, parallaxscale, specscale, ...

**Comment by slacka** [comment] 2015-01-30 02:58
@svenpanne 
Is issue #53 a duplicate of this bug? Also the precision mismatch issue is discussed at https://bugzilla.mozilla.org/show_bug.cgi?id=1094047

**Comment by svenpanne** [comment] 2015-01-30 08:52
Yep, that's a duplicate. It's nice to see that FireFox starts to follow the WebGL spec in a stricter way, too. :smiley:

**Comment by kripken** [comment] 2015-02-18 19:25
Updated the build, should be fixed.

**Closed by kripken** 2015-02-18 19:25 UTC
