### ISSUE TITLE
psychedelic on mac chrome

### ISSUE THREAD

**Issue by harry-wood** [kripken/BananaBread#53] opened 2014-09-03 23:19 UTC
Is it supposed to look psychedelic like this?

![psychedelic bright colours](https://farm6.staticflickr.com/5577/15132263152_2c7857b041.jpg)

Chrome version 37.0.2062.94
On MacOS X Version 10.9.4
Playing the "stable demo" at https://developer.mozilla.org/en-US/demos/detail/bananabread

**Comment by slacka** [comment] 2015-01-24 19:50
Somewhere between FF33 and FF35, something broke. BananaBread is now trippy in FF35 and 37.0a2 (2015-01-23). Also Chrome 39 and 42 Canary still have this bug in both Windows and Linux.

@harry-wood 
Topic should be changed to " psychedelic on all browers" now. 

@kripken 
Do you know the cause or do you need me to run a mozregression to find the commit that triggered this?

**Comment by kripken** [comment] 2015-01-25 05:12
Perhaps related to https://bugzilla.mozilla.org/show_bug.cgi?id=1124187 ?

**Comment by slacka** [comment] 2015-01-25 06:45
@kripken 
I'm on an Ubuntu 14.10 running FF 38.0a1 (2015-01-24) with proprietary Nvidia drivers and it's giving the trippy colors. Other Ubuntu 14.4 computer at home has been has this issue since FF 35 and it's using the Mesa drivers. Bug 1124187 is a Windows/ANGLE specific bug with black screen and textures, so I don't think this related to the psychedelic colors in BananaBread.  Are you having trouble reproducing it? Would a mozregression help you?

**Comment by kripken** [comment] 2015-01-25 17:08
@modeswitch , you're the only one that can update the full demo (with webrtc). Any chance you can do that?

I tried to update it now without webrtc, but there is some hosting error there. Another option is to take it down from there and use github pages.

**Comment by modeswitch** [comment] 2015-01-25 17:15
I thought I had landed everything, but I'll double-check. We need to find a new place to host the webrtc broker though.

I had lots of problems with the demo site. I opened bugs a long time ago, but they were closed without being fixed. My suggestion is to host it somewhere else.

**Comment by kripken** [comment] 2015-01-25 17:19
Heh, well I just filed earlier today https://bugzilla.mozilla.org/show_bug.cgi?id=1125630 , we'll see what happens. But yeah, I'm fine with hosting anywhere.

**Comment by modeswitch** [comment] 2015-01-25 18:35
@kripken Also, I have a webrtc implementation for node.js (datachannels only) that would work with emscripten: https://github.com/js-platform/node-webrtc. We should be able to compile a server using that code and use that instead of having one of the clients do it.

Thoughts?

**Comment by kripken** [comment] 2015-01-25 18:42
Sounds cool!

Although I'm a little disappointed that there hasn't been much interest in BananaBread. The cube 2 community hasn't shown enthusiasm, and I'm not aware of anyone running their own servers or anything like that. For those reasons, I'm not sure it makes sense to put much effort into improvements here. I guess BananaBread was a good first demo of a fully-functional FPS in browsers, but that was it's main usefulness.

**Comment by slacka** [comment] 2015-01-26 21:26
@kripken 
BananaBread is an impressive demonstration of what the Emscripten/WebGL tech are capable of. I think one of the reasons it it never caught on is that the webrtc did not work for most people. When it was first announced I made several attempts to find public matches and play with some friends. But we were never able to connect. I don't know if it was an issue with my Firefox or router, but I think it never worked for most people.

Another thing that would have pushed adoption/interest is a public server browser that shows number of players and where they're playing.

**Comment by modeswitch** [comment] 2015-01-26 21:49
@slacka BananaBread multiplayer was released when WebRTC was still pretty new. As a result, much of the NAT-traversal options that exist now weren't really working. Also, having one of the clients act as server isn't a good user experience.

Having a standalone server, and setting up STUN and TURN services would address these issues.

**Comment by slacka** [comment] 2015-01-30 02:54
@modeswitch 
Yes, I didn't mean to be critical of your work. It was just an observation that the demo was announced before the browsers were ready. Now that they have, it might might sense for Mozilla to show it off with a new release and announcement. Maybe a good project for an intern?

**Comment by modeswitch** [comment] 2015-01-30 03:11
@slacka I'm not offended! Your comments are valid and I appreciate the feedback.

I'm not sure if @kripken has any interns, but it would be a reasonably-sized project to update the demo with a standalone server and some better NAT traversal.

**Comment by kripken** [comment] 2015-01-30 05:24
No one that I am aware of. I agree it might be nice though.

**Comment by harry-wood** [comment] 2015-01-30 14:58
You're covering a few different topics here, one of which seems to be... how to "get some gaming happening".  Continue discussing that here? : https://github.com/kripken/BananaBread/issues/57

**Comment by slacka** [comment] 2015-02-10 02:26
@modeswitch 
> I thought I had landed everything, but I'll double-check. We need to find a new place to host the webrtc broker though.

According to  https://bugzilla.mozilla.org/show_bug.cgi?id=1125630 , they resolved the uploading problem with Demo Studio.

**Comment by kripken** [comment] 2015-02-10 04:10
@modeswitch , let me know if you want to upload a multiplayer version, or I can upload a singleplayer (at least without rendering glitches ;)

**Comment by modeswitch** [comment] 2015-02-10 22:53
@kripken Upload a new singleplayer version. If we want to host the multiplayer again, we'll need to find a place to host the webrtc broker. Or do the standalone server. That would be my preference because it's a more realistic example. That would require an additional developer resource.

**Comment by kripken** [comment] 2015-02-11 02:15
Ok, cool, uploaded.

People that saw the graphical glitches, please confirm they are fixed.

**Comment by slacka** [comment] 2015-02-18 08:54
Verified Fixed in both FF Nightly and Chrome Canary. You can close this and issues #42 now. Thanks kripken!

**Closed** 2015-02-18 19:25 UTC
